comment_service/comment_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('comments.urls', namespace='comments')),
    path('posts/', include('posts.urls', namespace='posts'))
]

comment_service/comments/urls.py
from django.urls import path, include
from .views import (
    CommentCreate, 
    CommentUpdate, 
    CommentDelete,
    PostCommentReply,
    PostCommentView
    )

app_name='comments'
urlpatterns = [
    path('<int:post_id>/create/', CommentCreate.as_view(), name='create'),
    path('create_comment/', PostCommentView.as_view(), name='create_com'),
    # path('<int:comment_id>/reply/', CommentReply.as_view(), name='reply'),
    path('<int:postcomment_id>/reply_post_comment/', PostCommentReply.as_view(), name='postcomment_reply'),
    path('<int:pk>/update/', CommentUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', CommentDelete.as_view(), name='delete'),
]

comment_service/posts/urls.py
''' Пути к постам и коментам '''
from django.urls import path
from .views import PostList, PostDetail, PostCommentChildren

app_name='posts'
urlpatterns = [
    path('', PostList.as_view(), name='list'),
    path('<slug:slug>/', PostDetail.as_view(), name='detail'),
    path('<int:parentcomment_id>/subcomments/', PostCommentChildren.as_view(), name='subcomments'),
]

comment_service/posts/models.py
"""Модель Post которая наследует поля Comment"""
from django.db import models
from django.urls import reverse


class Post(models.Model):
    """Поля модели Post"""
    title = models.CharField(max_length=150,
                            verbose_name='Название поста')
    slug = models.SlugField(max_length=150,
                            verbose_name='Слаг поста')
    body = models.TextField(blank=True,
                            verbose_name='Описание поста')
    date_pub = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Время создания поста')


    def get_absolute_url(self):
        """Путь к одному объекту модели Post"""
        return reverse('posts:detail', kwargs={'slug': self.slug})


    # @property
    # def get_comments(self):
    #     return comments.Comment.objects.all()


    def __str__(self):
        """Отображение название объекта"""
        return str(self.title)

comment_service/posts/views.py
"""
class PostList, где будет
отображаться список
объектов модели Post

class PostDetail, где будет
отображаться один объект Post,
и список комментариев с вложенностью
и пагинацией
"""
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView, MultipleObjectMixin
from django.views.generic.edit import FormView
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.views import View
from django.core import serializers
from django.shortcuts import get_object_or_404
from comments.models import Comment, PostComment, CommentHierarchy
from comments.forms import PostCommentForm
from .models import Post


class PostList(ListView):
    """Список объектов модели Post"""
    model = Post
    template_name = 'post_list.html'


    def get_queryset(self):
        return Post.objects.order_by('date_pub').reverse()


class PostDetail(DetailView):
    """
    один объект Post,
    и список комментариев с вложенностью
    и пагинацией
    """
    model = Post
    template_name = 'post_detail.html'
    # form_class = PostCommentForm
    success_url = reverse_lazy('posts:list')
    paginate_by = 3


    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        num_visits = self.request.session.get('num_visits', 0)
        self.request.session['num_visits'] = num_visits + 1
        context['comments'] = PostComment.objects.all()
        context['top_comments'] = PostComment.objects.filter(parent__isnull=True)
        context['sub_child'] = self.object.comments.filter(parent__isnull=False)
        context['post_comment_form'] = PostCommentForm(user=self.request.user, initial={'user': self.request.user, 'record': self.object})
        context['num_visits'] = num_visits
        depth = [dep for dep in PostComment.objects.filter(parent__isnull=True)]
        # print(self.object.comments.depth())
        print('dir', dir(PostComment.objects.filter(parent__isnull=True).filter(parents__depth__gte=0)))
        
        # print('dir', dir(self.object.comments.filter(parent__isnull=True)))
        # print(self.object.comments.filter(parent__isnull=True))

        return context


    def form_valid(self, form):
        form.save()
        return redirect(self.success_url)


class PostCommentChildren(View):

    model = Post
    template_name = 'post_detail.html'


    def get(self, request, *args, **kwargs):
        id_ = self.kwargs.get('parentcomment_id')
        post_comment = get_object_or_404(PostComment, pk=id_)
        hie = get_object_or_404(CommentHierarchy, pk=id_)
        # print(hie.parent.content)
        # print('POST COMMENT', post_comment)
        # print('POST COMMENT >>>>', post_comment.children.all())
        # print('POST COMMENT DIR', dir(post_comment.content))
        children = PostComment.objects.filter(parents__parent=id_)
        child = [child for child in post_comment.children.all()]
        # print('depth', post_comment.depth.depth)


        # print('Children', dir(child))
        # print()
        # print('Children', child)
        data = {
            'has_children': children.exists(),
            'children': list(children.values())
        }
        return JsonResponse(data)

comment_service/posts/templates/post_children.html
{% extends 'base.html' %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-md-2">
            {% block content %}
            
                <h1>Children</h1>
                {% for sub in all_comments %}
                    {{sub}}
                {% endfor %}

                <ul id='sub_children'>
                </ul>
            {% endblock %}
        </div>
    </div>
</div> 
{% block js %}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}

comment_service/posts/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-md-2">
            {% block content %}
            <h1>All Comments</h1>
            
                <h1>All First-Level Comments</h1>
                {% for comment in top_comments %}
                    <p><a href="{% url 'posts:subcomments' parentcomment_id=comment.id %}" data-commentid="{{ comment.id }}" data-depth = "{{ comment.depth }}" class="top-comment">{{ comment }} - {{ comment.depth.depth }}</a></p>
                    <ul class='children-{{ comment.id }}' data-depth = "{{ comment.depth }}">
                    </ul>
                {% endfor %}
                

            
            <hr>
            <form action="{% url 'comments:create_com' %}" method="post" id="comment_form">
                <input type="hidden" name="comment_id">
                <input type="hidden" name="record_id">
                    {% csrf_token %}
                    {{ post_comment_form }}
                <input type="submit" value='Оставить комментарий'>
            </form>
                <div class="mb-4"></div>
                <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
            {% endblock %}
        </div>
    </div>
</div> 
{% block js %}
<script src="{% static 'js/jquery.js'%}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}

comment_service/posts/templates/post_list.html
{% extends 'base.html' %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-md-2">
            {% block content %}
            <h1 class="mt-3">Posts</h1>
            {% for post in object_list %}
            <div class="card mt-3">
                <div class="card-header">
                    {{ post.date_pub }}
                </div>
                <div class="card-body">
                  <h5 class="card-title">{{ post.title }}</h5>
                  <p class="card-text">{{ post.body }}</p>
                  <a href="{% url 'posts:detail' slug=post.slug %}" class="btn btn-primary">Detail</a>
                </div>
              </div>
              {% endfor %}
            {% endblock %}
        </div>
    </div>
</div> 